# Generated by Django 4.1.3 on 2022-11-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default="lb", max_length=255),
        ),
    ]
