# Generated by Django 4.1.3 on 2022-11-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_product_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(default="lb", max_length=255),
        ),
    ]
